# Generated by Django 5.1.5 on 2025-05-29 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_unidadecargo_pontos_total_unidadecargo_valor_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Simulação')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('estrutura_atual', models.TextField(help_text='Dados da estrutura atual em formato JSON', verbose_name='Estrutura Atual (JSON)')),
                ('estrutura_nova', models.TextField(help_text='Dados da estrutura nova em formato JSON', verbose_name='Estrutura Nova (JSON)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Simulação',
                'verbose_name_plural': 'Simulações',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100, verbose_name='Área')),
                ('cargo_type', models.CharField(max_length=100, verbose_name='Tipo do Cargo')),
                ('denominacao', models.CharField(max_length=255, verbose_name='Denominação')),
                ('categoria', models.IntegerField(verbose_name='Categoria')),
                ('nivel', models.IntegerField(verbose_name='Nível')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('pontos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pontos')),
                ('is_estrutura_nova', models.BooleanField(default=False, verbose_name='É Estrutura Nova')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.simulation')),
            ],
            options={
                'verbose_name': 'Posição',
                'verbose_name_plural': 'Posições',
            },
        ),
    ]
