# Generated by Django 5.1.5 on 2025-06-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_relatorio_relatorioefetivo_relatoriogratificacoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorioorgaoscentrais',
            name='relatorio',
        ),
        migrations.RemoveField(
            model_name='relatorioefetivo',
            name='relatorio',
        ),
        migrations.RemoveField(
            model_name='relatoriogratificacoes',
            name='relatorio',
        ),
        migrations.AddField(
            model_name='relatorioefetivo',
            name='data_importacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Importação'),
        ),
        migrations.AddField(
            model_name='relatoriogratificacoes',
            name='data_importacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Importação'),
        ),
        migrations.AddField(
            model_name='relatorioorgaoscentrais',
            name='data_importacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Importação'),
        ),
        migrations.DeleteModel(
            name='Relatorio',
        ),
    ]
