# Generated by Django 5.1.5 on 2025-06-16 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_relatorioefetivo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True, verbose_name='Chave de Configuração')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario_atualizacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Atualizou')),
            ],
            options={
                'verbose_name': 'Configuração de Relatório',
                'verbose_name_plural': 'Configurações de Relatórios',
                'ordering': ['chave'],
            },
        ),
        migrations.CreateModel(
            name='Decreto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True, verbose_name='Número do Decreto')),
                ('data_publicacao', models.DateField(verbose_name='Data de Publicação')),
                ('titulo', models.TextField(verbose_name='Título/Ementa')),
                ('tipo', models.CharField(choices=[('estrutura_regimental', 'Estrutura Regimental'), ('reorganizacao', 'Reorganização'), ('criacao', 'Criação de Órgão'), ('extincao', 'Extinção de Órgão'), ('alteracao', 'Alteração'), ('outro', 'Outro')], max_length=50, verbose_name='Tipo de Decreto')),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('revogado', 'Revogado'), ('alterado', 'Alterado')], default='vigente', max_length=20, verbose_name='Status')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='decretos/', verbose_name='Arquivo do Decreto')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('usuario_cadastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Cadastrou')),
            ],
            options={
                'verbose_name': 'Decreto',
                'verbose_name_plural': 'Decretos',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoPermuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servidor1', models.CharField(max_length=255, verbose_name='Nome do Servidor 1')),
                ('matricula_servidor1', models.CharField(max_length=50, verbose_name='Matrícula SIAPE Servidor 1')),
                ('unidade_servidor1', models.CharField(max_length=255, verbose_name='Unidade do Servidor 1')),
                ('nome_servidor2', models.CharField(max_length=255, verbose_name='Nome do Servidor 2')),
                ('matricula_servidor2', models.CharField(max_length=50, verbose_name='Matrícula SIAPE Servidor 2')),
                ('unidade_servidor2', models.CharField(max_length=255, verbose_name='Unidade do Servidor 2')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_analise', models.DateTimeField(blank=True, null=True, verbose_name='Data da Análise')),
                ('observacoes_analise', models.TextField(blank=True, verbose_name='Observações da Análise')),
                ('usuario_analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_permuta', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Analista')),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação de Permuta',
                'verbose_name_plural': 'Solicitações de Permuta',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoRealocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servidor', models.CharField(max_length=255, verbose_name='Nome do Servidor')),
                ('matricula_siape', models.CharField(max_length=50, verbose_name='Matrícula SIAPE')),
                ('unidade_atual', models.CharField(max_length=255, verbose_name='Unidade Atual')),
                ('unidade_destino', models.CharField(max_length=255, verbose_name='Unidade Destino')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_analise', models.DateTimeField(blank=True, null=True, verbose_name='Data da Análise')),
                ('observacoes_analise', models.TextField(blank=True, verbose_name='Observações da Análise')),
                ('usuario_analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_realocacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Analista')),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação de Realocação',
                'verbose_name_plural': 'Solicitações de Realocação',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
