# Generated by Django 5.2.2 on 2025-07-02 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_configuracaorelatorio_decreto_solicitacaopermuta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacaosalva',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('enviada_analise', 'Enviada para Análise'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='rascunho', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='simulacaosalva',
            name='tipo_usuario',
            field=models.CharField(choices=[('externo', 'Usuário Externo'), ('interno', 'Usuário Interno'), ('gerente', 'Usuário Gerente')], default='externo', max_length=10, verbose_name='Tipo de Usuário'),
        ),
        migrations.AddField(
            model_name='simulacaosalva',
            name='visivel_para_gerentes',
            field=models.BooleanField(default=False, verbose_name='Visível para Gerentes'),
        ),
        migrations.CreateModel(
            name='SolicitacaoSimulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Solicitação')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('unidade_base_sugerida', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidade Base Sugerida')),
                ('prazo_estimado', models.DateField(blank=True, null=True, verbose_name='Prazo Estimado')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=15, verbose_name='Status')),
                ('aceita_em', models.DateTimeField(blank=True, null=True, verbose_name='Aceita em')),
                ('observacoes_usuario', models.TextField(blank=True, null=True, verbose_name='Observações do Usuário')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('simulacao_criada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.simulacaosalva', verbose_name='Simulação Criada')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_feitas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante (Gerente)')),
                ('usuario_designado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Designado')),
            ],
            options={
                'verbose_name': 'Solicitação de Simulação',
                'verbose_name_plural': 'Solicitações de Simulações',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoSimulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nova_solicitacao', 'Nova Solicitação'), ('simulacao_enviada', 'Simulação Enviada para Análise'), ('solicitacao_aceita', 'Solicitação Aceita'), ('simulacao_aprovada', 'Simulação Aprovada'), ('simulacao_rejeitada', 'Simulação Rejeitada')], max_length=20, verbose_name='Tipo de Notificação')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('simulacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.simulacaosalva', verbose_name='Simulação Relacionada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('solicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.solicitacaosimulacao', verbose_name='Solicitação Relacionada')),
            ],
            options={
                'verbose_name': 'Notificação de Simulação',
                'verbose_name_plural': 'Notificações de Simulações',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('externo', 'Usuário Externo'), ('interno', 'Usuário Interno'), ('gerente', 'Usuário Gerente')], default='externo', max_length=10, verbose_name='Tipo de Usuário')),
                ('pode_solicitar', models.BooleanField(default=False, verbose_name='Pode Solicitar Simulações')),
                ('pode_ver_todas', models.BooleanField(default=False, verbose_name='Pode Ver Todas as Simulações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_usuario_simulacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Usuário',
                'verbose_name_plural': 'Tipos de Usuários',
            },
        ),
    ]
