# Generated by Django 5.1.5 on 2025-07-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_adicionar_status_rejeitada_editada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipousuario',
            name='restrito_unidade',
            field=models.BooleanField(default=False, help_text='Se marcado, usuário só pode criar simulações da sua unidade', verbose_name='Restrito à Sua Unidade'),
        ),
        migrations.AddField(
            model_name='tipousuario',
            name='unidade_nome',
            field=models.CharField(blank=True, help_text='Ex: Assessoria de Participação Social e Diversidade', max_length=255, null=True, verbose_name='Nome Completo da Unidade'),
        ),
        migrations.AddField(
            model_name='tipousuario',
            name='unidade_sigla',
            field=models.CharField(blank=True, help_text='Ex: ASPAD, CGE, DIPAF. Define a área de atuação do usuário interno', max_length=20, null=True, verbose_name='Sigla da Unidade'),
        ),
    ]
