# Generated by Django 5.1.5 on 2025-07-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_adicionar_limitacao_unidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipousuario',
            name='restrito_unidade',
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='unidade_nome',
            field=models.CharField(blank=True, help_text='Nome completo da unidade (ex: Assessoria de Participação Social e Diversidade)', max_length=255, null=True, verbose_name='Nome da Unidade'),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='unidade_sigla',
            field=models.CharField(blank=True, help_text='Sigla da unidade que o usuário pode editar (ex: ASPAD, CGCIN, etc.)', max_length=20, null=True, verbose_name='Sigla da Unidade'),
        ),
    ]
