# Generated by Django 5.1.5 on 2025-07-04 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_adicionar_unidade_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(help_text='Sigla da unidade (ex: ASPAD, CGCIN, DIPAF)', max_length=20, unique=True, verbose_name='Sigla')),
                ('nome_completo', models.CharField(help_text='Nome completo da unidade', max_length=255, verbose_name='Nome Completo')),
                ('descricao', models.TextField(blank=True, help_text='Descrição adicional sobre a unidade', null=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, help_text='Se a unidade está ativa para atribuição a usuários', verbose_name='Ativa')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['sigla'],
            },
        ),
        migrations.RemoveField(
            model_name='tipousuario',
            name='unidade_nome',
        ),
        migrations.RemoveField(
            model_name='tipousuario',
            name='unidade_sigla',
        ),
        migrations.AddField(
            model_name='tipousuario',
            name='unidade',
            field=models.ForeignKey(blank=True, help_text='Unidade que o usuário interno pode editar. Gerentes podem editar qualquer unidade.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unidade', verbose_name='Unidade'),
        ),
    ]
