# Generated by Django 5.1.5 on 2025-07-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_unidade_remove_tipousuario_unidade_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipousuario',
            name='unidade',
        ),
        migrations.AddField(
            model_name='tipousuario',
            name='unidade_nome',
            field=models.CharField(blank=True, help_text='Nome completo da unidade', max_length=255, null=True, verbose_name='Nome da Unidade'),
        ),
        migrations.AddField(
            model_name='tipousuario',
            name='unidade_sigla',
            field=models.CharField(blank=True, help_text='Sigla da unidade que o usuário pode editar (ex: ASPAD, CGCIN, etc.)', max_length=20, null=True, verbose_name='Sigla da Unidade'),
        ),
        migrations.DeleteModel(
            name='Unidade',
        ),
    ]
