# Generated by Django 5.1.5 on 2025-07-08 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_tipousuario_unidade_tipousuario_unidade_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipousuario',
            name='unidade_nome',
        ),
        migrations.RemoveField(
            model_name='tipousuario',
            name='unidade_sigla',
        ),
        migrations.AddField(
            model_name='unidadecargo',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para cargos padrão do sistema', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Criador'),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='tipo',
            field=models.CharField(choices=[('externo', 'Usuário Externo'), ('interno', 'Usuário Interno'), ('gerente', 'Usuário Gerente (SE)')], default='externo', max_length=10, verbose_name='Tipo de Usuário'),
        ),
    ]
