# Generated by Django 5.1.5 on 2025-02-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UnidadeCargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel_hierarquico",
                    models.IntegerField(verbose_name="Nível Hierárquico"),
                ),
                (
                    "tipo_unidade",
                    models.CharField(max_length=100, verbose_name="Tipo Unidade"),
                ),
                (
                    "denominacao_unidade",
                    models.CharField(
                        max_length=255, verbose_name="Denominação Unidade"
                    ),
                ),
                (
                    "codigo_unidade",
                    models.CharField(max_length=50, verbose_name="Código Unidade"),
                ),
                (
                    "sigla_unidade",
                    models.CharField(max_length=50, verbose_name="Sigla Unidade"),
                ),
                (
                    "categoria_unidade",
                    models.CharField(max_length=100, verbose_name="Categoria Unidade"),
                ),
                (
                    "orgao_entidade",
                    models.CharField(max_length=255, verbose_name="Órgão / Entidade"),
                ),
                (
                    "tipo_cargo",
                    models.CharField(max_length=100, verbose_name="Tipo do Cargo"),
                ),
                (
                    "denominacao",
                    models.CharField(max_length=255, verbose_name="Denominação"),
                ),
                (
                    "complemento_denominacao",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Complemento Denominação",
                    ),
                ),
                ("categoria", models.IntegerField(verbose_name="Categoria")),
                ("nivel", models.IntegerField(verbose_name="Nível")),
                ("quantidade", models.IntegerField(verbose_name="Quantidade")),
                ("grafo", models.CharField(max_length=100, verbose_name="Grafo")),
                ("sigla", models.CharField(max_length=100, verbose_name="Sigla")),
            ],
        ),
    ]
