# Generated by Django 5.1.5 on 2025-02-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadecargo',
            name='nivel',
            field=models.IntegerField(default=1, verbose_name='Nível'),
        ),
        migrations.AlterField(
            model_name='unidadecargo',
            name='orgao_entidade',
            field=models.CharField(max_length=255, verbose_name='Órgão/Entidade'),
        ),
    ]
