# Generated by Django 5.1.5 on 2025-02-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_unidadecargo_nivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadecargo',
            name='categoria',
            field=models.IntegerField(default=1, verbose_name='Categoria'),
        ),
    ]
