# Generated by Django 5.1.5 on 2025-03-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_unidadecargo_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidadecargo",
            name="categoria",
            field=models.IntegerField(verbose_name="Categoria"),
        ),
        migrations.AlterField(
            model_name="unidadecargo",
            name="nivel",
            field=models.IntegerField(verbose_name="Nível"),
        ),
    ]
