# Generated by Django 5.1.5 on 2025-03-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_cargosiorg_unitario"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadecargo",
            name="pontos_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Pontos Total"
            ),
        ),
        migrations.AddField(
            model_name="unidadecargo",
            name="valor_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Valor Total"
            ),
        ),
    ]
