# Generated by Django 5.1.5 on 2025-05-29 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_simulation_usuario_anexotemplate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanilhaImportada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="planilhas_importadas/",
                        verbose_name="Arquivo da Planilha",
                    ),
                ),
                (
                    "data_importacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Importação"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planilha Importada",
                "verbose_name_plural": "Planilhas Importadas",
                "ordering": ["-data_importacao"],
            },
        ),
        migrations.DeleteModel(
            name="AnexoTemplate",
        ),
    ]
