# Generated by Django 5.1.5 on 2025-05-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_planilhaimportada_delete_anexotemplate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planilhaimportada",
            name="usuario",
        ),
        migrations.AddField(
            model_name="planilhaimportada",
            name="ativo",
            field=models.BooleanField(default=False, verbose_name="Planilha Ativa"),
        ),
    ]
