# Generated by Django 5.1.5 on 2025-05-30 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_planilhaimportada_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacaoSalva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome descritivo para identificar a simulação', max_length=100, verbose_name='Nome da Simulação')),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional da simulação', null=True, verbose_name='Descrição')),
                ('dados_estrutura', models.JSONField(help_text='Dados JSON da estrutura simulada', verbose_name='Dados da Estrutura Nova')),
                ('unidade_base', models.CharField(blank=True, help_text='Sigla da unidade base da simulação', max_length=50, null=True, verbose_name='Unidade Base')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Simulação Salva',
                'verbose_name_plural': 'Simulações Salvas',
                'ordering': ['-atualizado_em'],
                'unique_together': {('usuario', 'nome')},
            },
        ),
    ]
