# Generated by Django 5.1.5 on 2025-06-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_relatoriogratificacoesplan1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relatoriogratificacoes",
            name="cpf",
        ),
        migrations.RemoveField(
            model_name="relatoriogratificacoes",
            name="cpf_substituto",
        ),
        migrations.RemoveField(
            model_name="relatoriogratificacoes",
            name="cpf_titular_chefe",
        ),
    ]
