# Generated by Django 5.1.5 on 2025-07-10 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_adicionar_status_rejeitada_editada"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadecargo",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                help_text="Deixe em branco para cargos padrão do sistema",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário Criador",
            ),
        ),
    ]
